# Installs needed to run the R code in this folder

install.packages('BiocManager')
BiocManager::install('clusterProfiler', dependencies= TRUE, force=TRUE)
BiocManager::install('RDAVIDWebService')  # not available for Bioconductor 3.18
BiocManager::install('BiocVersion') 
BiocManager::install('topGO')
BiocManager::install('org.Hs.eg.db', dependencies= TRUE, force=TRUE)
BiocManager::install('GOstats')
BiocManager::install('AnnotationDbi')
BiocManager::install('DOSE') 
BiocManager::install("GenomeInfoDbData")
BiocManager::install("HDO.db")
BiocManager::install("biomaRt")
BiocManager::install("STRINGdb")
BiocManager::install("KEGGREST")
BiocManager::install("KEGGgraph")
BiocManager::install("AnnotationHub")
install.packages("igraph")
install.packages("readxl")
install.packages("readr")
install.packages("igraph")
install.packages("visNetwork")
install.packages("pROC")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("purrr")
install.packages("stringr")
install.packages("httr")
install.packages("KEGGREST")
install.packages("here")